### ISSUE TITLE
Example Functional Tests don't succeed due to selenium/geckodriver issue

### ISSUE THREAD

**Issue by Standard8** [mozilla/example-addon-repo#1]
The example functional tests currently don't succeed due to an issue in selenium or geckodriver.

See https://github.com/mozilla/geckodriver/issues/204 and https://github.com/mozilla/geckodriver/issues/205 for details.

**Comment by Standard8** [comment]
The issue isn't with geckodriver, it is with selenium, pull request now up: https://github.com/SeleniumHQ/selenium/pull/2718

**Comment by dmose** [comment]
Following the chain of issues up to its root in SeleniumHQ, they've merged your PR there, so can this be closed?

**Comment by Standard8** [comment]
I need to get the required changes landed in this repo to close this out - basically, update selenium & get the tests working. I was having a problem with the windows builders though, so I may need to debug that as well. Hopefully will get to it soon.

**Comment by dmose** [comment]
Cool; thanks for the update!
